input {
  tcp {
    port => 5959
    codec => json
  }
}

filter {
  if [message] !~ /^python-logstash:/ {
    drop { }
  }

  if [extra][top_word] {
    mutate {
      add_field => { "top_word" => "%{[extra][top_word]}" }
    }
  }

  if [extra][sentence] {
    mutate {
      add_field => { "sentence" => "%{[extra][sentence]}" }
    }
  }

  if [top_word] {
    mutate {
      lowercase => [ "top_word" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "python-logstash-homework-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
